# Generated by Django 6.0.1 on 2026-01-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_song_cover_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="song",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="song",
            name="audio_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
