# Generated by Django 6.0.1 on 2026-02-16 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_remove_song_audio_file_remove_song_cover_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="audio_url",
        ),
        migrations.RemoveField(
            model_name="song",
            name="cover_url",
        ),
        migrations.AddField(
            model_name="song",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="songs/"),
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="song",
            name="play_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="song",
            name="artist",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="RecentlyPlayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played_at", models.DateTimeField(auto_now=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
    ]
